name: SkyPrint
version: 1.0.0
main: pw.ollie.skyprint.SkyPrint

commands:
    skywrite:
        description: Writes a message in the sky
    skyundo:
        description: Undoes last edit

permission:
    skyprint.use:
        description: Allows usage of SkyPrint
